name: Tests

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    runs-on: macOS-latest
    env:
      POD_PATH: example/Pods
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Cache ${{ env.POD_PATH }}
        uses: actions/cache@v4
        with:
          path: ${{ env.POD_PATH }}
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-

      - name: Environment
        run: |
          xcodebuild -version
          swift -version

      - name: Run tests
        run: |
          cd example
          bundle install
          bundle exec fastlane test

      - name: Rspec
        run: |
          bundle install
          bundle exec rspec spec
